spring:
  application:
    name: yonchain
  datasource:
    url: jdbc:postgresql://42.194.189.63:35432/yonchain
    username: dify4j
    password: dify4j
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 42.194.189.63
      password: 123456
      port: 26739
      database: 8
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080
  security:
    debug: true

yonchain:
  version: 0.1.0
  security:
    password-encoder-type: dify@pbkdf2
    enable-password-encoder-prefix: ${DIFY4J_PASSWORD_ENCODER_PREFIX:true}
    oauth2:
      jwt:
      #private-key: ${JWT_PRIVATE_KEY}  # 从环境变量读取
        # public-key: ${JWT_PUBLIC_KEY}    # 从环境变量读取
      #  kid: ${JWT_KEY_ID}                # Key ID 也可通过环境变量配置
      authorizationserver:
        captcha-enabled: false
      resourceserver:
        permit-paths:
          - ${DIFY4J_RESOURCESERVER_PERMIT_PATHS:/api/**}  # 从环境变量读取
          - ${DIFY4J_RESOURCESERVER_PERMIT_PATHS2:/token/check_token}  # 从环境变量读取
    # dify-secret-key: ${DIFY_SECRET_KEY}  # 从环境变量读取


mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    "com.yonchain.ai.*.mapper": DEBUG

    # 或者针对特定的mapper文件进行设置
    com.yonchain.ai.**.mapper: DEBUG
    com.yonchain.ai.app.mapper: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE
    org.springframework.security.authentication: TRACE

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    oauth:
      use-pkce-with-authorization-code-grant: true
    doc-expansion: none
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  group-configs:
    - group: Dify4j开发平台
      paths-to-match: /**
  cache:
    disabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
