package com.yonchain.ai.agent;

/**
 * This interface provides methods to access the main output of the AI app and the
 * metadata associated with this result. It is designed to offer a standardized and
 * comprehensive way to handle and interpret the outputs generated by AI apps, catering
 * to diverse AI applications and use cases.
 *
 * @param <T> the type of the output generated by the AI app
 * @author Cgy
 * @since 0.1.0
 */
public interface AppResult<T> {

    /**
     * Retrieves the output generated by the AI app.
     * @return the output generated by the AI app
     */
    T getOutput();

    /**
     * Retrieves the metadata associated with the result of an AI app.
     * @return the metadata associated with the result
     */
    ResultMetadata getMetadata();

}
