package com.yonchain.ai.agent;
/**
 * Interface representing metadata associated with the results of an AI app. This
 * interface focuses on providing additional context and insights into the results
 * generated by AI apps. It could include information like computation time, app
 * version, or other relevant details that enhance understanding and management of AI
 * app outputs in various applications.
 *
 * @author Cgy
 * @since 0.1.0
 */
public interface ResultMetadata {
}
