package com.yonchain.ai.app;

import java.util.List;

/**
 * Interface representing the response received from an AI app. This interface provides
 * methods to access the main result or a list of results generated by the AI app, along
 * with the response metadata. It serves as a standardized way to encapsulate and manage
 * the output from AI apps, ensuring easy retrieval and processing of the generated
 * information.
 *
 * @param <T> the type of the result(s) provided by the AI app
 * @author Cgy
 * @since 0.1.0
 */
public interface AppResponse<T  extends AppResult<?>> {

    /**
     * Retrieves the result of the AI app.
     *
     * @return the result generated by the AI app
     */
    T getResult();

    /**
     * Retrieves the list of generated outputs by the AI app.
     *
     * @return the list of generated outputs
     */
    List<T> getResults();

    /**
     * Retrieves the response metadata associated with the AI app's response.
     *
     * @return the response metadata
     */
    ResponseMetadata getMetadata();

}
